### ISSUE TITLE
Randomización de las preguntas de elecciones

### ISSUE THREAD

**Issue by DanielaVLl** [verduralegorica/Experimento_meds#6]
En el caso de las sección de elecciones, ya hemos randomizado el orden, pero solo salen las imágenes, no las preguntas.

**Comment by mgutierrezc** [comment]
Usar la misma lógica de la aleatorizacion de las páginas para las pregs. Por ej, usar el diccionario pes pags y que llame a una pregunta en particular

**Comment by mgutierrezc** [comment]
Vayan subiendo su progreso y lo veo durante la semana. No esperen a que yo lo vea y les de una solución. Si ven que lo pueden ir avanzando por su cuenta o creen que algo lo puede solucionar, tienen la libertad de hacerlo. Yo no siempre podré comentar/tener reuniones
