### ISSUE TITLE
Pay-off

### ISSUE THREAD

**Issue by DanielaVLl** [verduralegorica/Experimento_meds#7]
Colocamos el pay-off, pero este solo aparece cuando adelantamos en progress a partir de 15/14 pages, pero no antes.

**Comment by mgutierrezc** [comment]
Revisen la sección de payoffs en la documentación

**Comment by mgutierrezc** [comment]
No entiendo el “solo aparece”. Se refieren a que los pagos solo se calculan bien si llegan a 15/14 o a qué en esa página se muestran?

Tal vez puede ser porque set_payoffs debería ser llamado antes.

**Comment by DanielaVLl** [comment]
Si, recién el pay-off se calcula en 15/14, antes aparece 0.

**Comment by mgutierrezc** [comment]
Revísenlo y vayan subiendo sus avances por aquí. Este issue no debería tenerme asignado, pues yo no me encargare directamente de programar la solución de este código.
